In [2]:
import numpy as np

data = np.array([
    [25, 50000, 1],
    [30, np.nan, 0],
    [np.nan, 45000, 1],
    [28, 52000, np.nan]
])
print(data)

[[2.5e+01 5.0e+04 1.0e+00]
 [3.0e+01     nan 0.0e+00]
 [    nan 4.5e+04 1.0e+00]
 [2.8e+01 5.2e+04     nan]]


In [8]:
age = data[:, 0]
print(age)
salary = data[:, 1]
label = data[:, 2]
print(salary)
print(label)

[25. 30. nan 28.]
[50000.    nan 45000. 52000.]
[ 1.  0.  1. nan]


In [13]:
age_mean = np.nanmean(age)
salary_mean=np.nanmean(salary)
print(age_mean)
print(salary_mean)

27.666666666666668
49000.0


In [15]:
age[np.isnan(age)] = age_mean
salary[np.isnan(salary)] = salary_mean

In [17]:
labels_non_nan = label[~np.isnan(label)]
mode = np.bincount(labels_non_nan.astype(int)).argmax()
label[np.isnan(label)] = mode

In [19]:
cleaned_data = np.column_stack((age, salary, label))

print(cleaned_data)

[[2.50000000e+01 5.00000000e+04 1.00000000e+00]
 [3.00000000e+01 4.90000000e+04 0.00000000e+00]
 [2.76666667e+01 4.50000000e+04 1.00000000e+00]
 [2.80000000e+01 5.20000000e+04 1.00000000e+00]]


In [24]:
data = np.array([
    [25, 50000],
    [30, 60000],
    [65, 80000]
])
print(data)

[[   25 50000]
 [   30 60000]
 [   65 80000]]


In [31]:
# Normalization
min_vals = data.min(axis=0)
max_vals = data.max(axis=0)
normalized = (data - min_vals) / (max_vals - min_vals)


In [33]:
mean = data.mean(axis=0)
std = data.std(axis=0)
print(mean)
print(std)
standardized = (data - mean) / std

print("Normalized:\n", normalized)
print("Standardized:\n", standardized)

[4.00000000e+01 6.33333333e+04]
[   17.79513042 12472.19128925]
Normalized:
 [[0.         0.        ]
 [0.125      0.33333333]
 [1.         1.        ]]
Standardized:
 [[-0.84292723 -1.06904497]
 [-0.56195149 -0.26726124]
 [ 1.40487872  1.33630621]]


In [34]:
categories = np.array(["cat", "dog", "cat", "bird"])

unique = np.unique(categories)

# Create mapping
mapping = {val: idx for idx, val in enumerate(unique)}

# One-hot encoding
one_hot = np.zeros((len(categories), len(unique)))

for i, val in enumerate(categories):
    one_hot[i, mapping[val]] = 1

print(one_hot)

[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


In [36]:
X = np.arange(20).reshape(10,2)
y = np.array([0,1,0,1,0,1,0,1,0,1])

# Shuffle
indices = np.random.permutation(len(X))

X = X[indices]
y = y[indices]

# Split
split = int(0.8 * len(X))

X_train, X_test = X[:split], X[split:]
y_train, y_test = y[:split], y[split:]

print(X_train, X_test)

[[ 4  5]
 [ 8  9]
 [10 11]
 [ 0  1]
 [18 19]
 [ 2  3]
 [12 13]
 [16 17]] [[ 6  7]
 [14 15]]


In [39]:
image = np.random.randint(0, 255, (224, 224, 3))

# Normalize
image_normalized = image / 255.0
# Convert to grayscale
R = image[:,:,0]
G = image[:,:,1]
B = image[:,:,2]

gray = 0.299*R + 0.587*G + 0.114*B

print(gray.shape)

(224, 224)


In [40]:
data = np.array([
    [2, 3],
    [4, 5],
    [6, 7]
])

x = data[:, 0]
y = data[:, 1]

x_squared = x ** 2
xy = x * y

new_features = np.column_stack((x, y, x_squared, xy))

print(new_features)

[[ 2  3  4  6]
 [ 4  5 16 20]
 [ 6  7 36 42]]


In [41]:
data = np.random.rand(5,3)

corr_matrix = np.corrcoef(data, rowvar=False)

print(corr_matrix)

[[1.         0.76689274 0.10366424]
 [0.76689274 1.         0.26923516]
 [0.10366424 0.26923516 1.        ]]


In [42]:
y = np.array([0,0,0,0,1])

# Find minority class
unique, counts = np.unique(y, return_counts=True)

minority_class = unique[np.argmin(counts)]

# Get indices
minority_indices = np.where(y == minority_class)[0]

# Oversample
oversampled_indices = np.random.choice(minority_indices, size=counts.max(), replace=True)

balanced_y = np.concatenate([y, y[oversampled_indices]])

print(balanced_y)

[0 0 0 0 1 1 1 1 1]


In [43]:
data = np.array([1,2,3,4,5,6])

window_size = 3

windows = []

for i in range(len(data) - window_size + 1):
    windows.append(data[i:i+window_size])

windows = np.array(windows)

print(windows)

[[1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
